### ISSUE TITLE
Implement: Store::retrieve()

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#103]

**Comment by matthiasbeyer** [comment]
@TheNeikos

**Comment by neithernut** [comment]
I just found an issue with the existing partial implementation of the `Store::retrieve()` method introduced in commit https://github.com/matthiasbeyer/imag/commit/d949cddc650fb2fd0f87d81307b11815e8230db0. The code currently
 * acquired a lock of the hashmap
 * tries to get an _existing_ store entry from the hashmap
 * gets an entry from the store entry
 * constructs a `FileLockEntry` from it

In other words: the current code for `store::retrieve()` presumes that the entry is already in the hash map, which is obviously wrong. Moreover, the code doesn't even check whether the existing store entry is borrowed or not.
The correct way to perform a retrieve would be to assert no entry with a matching id exists in the hashmap, instead of querying the entry.

----

It's kinda embarrassing that I didn't note this earlier.

**Comment by neithernut** [comment]
IMO this also illustrates why having `get_entry()` on `StoreEntry` instead of having a private method on `Store` or an alternative constructor on `Entry` (taking a serialized entry) provides a fallacy people fall for.

**Comment by neithernut** [comment]
I also just noticed that we have `StoreErrorKind::IdLocked` and `StoreErrorKind::EntryAlreadyBorrowed`, which mean the same thing.

**Comment by neithernut** [comment]
Mh... this might even be used as a prime example why even the strictest type system, which saves your butt most of the time, can still be improved by statically proven contracts.
