### ISSUE TITLE
Use clap to generate bash compl?

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#495]
This might be complicated, actually, as we have a multi-crate setup here.

But it might be worth a try.

It would us require to update clap to `2.9.*`.

**Comment by matthiasbeyer** [comment]
clap is already updated to 2.11 or something like this, so this is not a blocker anymore.

@mario-kr do you want to play around with this maybe? Could be an awesome playground for some rust/bash things...

**Comment by mario-kr** [comment]
@matthiasbeyer 
a simple test for bash/fish-completion for the crate imag-todo:
https://github.com/mario-kr/imag/tree/test_clapcompl/imag-todo
For this single crate, the completions for bash work in the first level (typing in imag-todo and tab will show all subcommands and options), but not for the subcommands. In fish, the completions are reduced to the subcommand, and, again, only work in the first level (no options displayed).
We should consider waiting until the feature works better. Though I guess our setup could also be the cause for it not working completely right.
As for the multi-crate setup problem, I'd have to look into bash and fish completions myself to somewhat build a script to combine all completions.

**Comment by matthiasbeyer** [comment]
@kbknapp see what @mario-kr said,... I'm not sure how much should work out of the box with the autocomplete feature, but I guess options should work, right?

Also, @kbknapp, if you want to play around with our multi-crate setup and completions ... feel free to do so, if you're interested! Would love to see how that works.

**Comment by kbknapp** [comment]
@matthiasbeyer @mario-kr 

I'm not sure if it's just the setup that causes this, but I would suspect so without looking into too far. Only because this isn't an issue for `rustup` which uses heavily nested subcommands. 

Also note that the different shells have different levels of features/support. i.e. Zsh will show potential values for certain args, but Bash doesn't, etc. Things like that.

Finally, the completion script generation is meant to be a no maintenance feature in the best case, but for some projects it may just a be a "template" so to speak, where additional massaging may be required. Think of it like a 90% solution in the worse case :wink:
