### ISSUE TITLE
Multiple binaries

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#58]
I would like to split up the modules and the store into several modules, where one binary can use other binaries as libraries.

For example if we have one binary `imag-store`, this one implements an interface to the store. It can be used by the user from the commandline to inspect the store, but also exports a library which can be used by (for example) `imag-bm` to access the store.

This would be the git model of how the things are seperated. Additional thoughts must be put into this, as I'm not sure whether the binaries (`bm`, `notes`,...) should actually call the `store` binary or whether the `store` binary should be compiled into the others as a library.

Anyways, this is just an issue to remember this and collect some ideas. This is not achievable in the _near_ future.

**Comment by TheNeikos** [comment]
I've thought about it and this is what got out in the end:

---

One thing one wants to avoid when making applications is to nedlessly repeat yourself. Thus, making a library first and then a binary wrapper around it makes sense. 

That way:

1. The important parts of the library are exported
2. One can easily manage dependencies between library versions, since you compile against another, the binary you get is _final_

**A problem appears though** The store is not static, items evolve, new ones get added, old ones renamed or removed. Thus there is a need for versioning, `Semver` seems to be a sane choic. The first idea would be to namespace the modules, so if you had the module `ferhnrohrer` at version `0.3.3`, it's items would be at `fernrohrer-v0.3.3`. 

However, this could easily fragment the whole database to obscene levels. Imagine having dozens of different libraries, each potentially talking to different versions of stores! This could work if the Store does some more heavy lifting. If one imagines that the store reserves the first level and only allows abstract paths from there on, one could imagine it like this:

```rust
    module_path!("fernrohrer", Semver::parse("0.3.2")); # Creates a struct called ModulePath    

    // Somewhere in a function

    let store = Store::new();
    let item = store.get_item(ModulePath::new("search/do_snake_ballons_hiss_when_scared"));
    let all_items = store.get_all_for(ModulePath::root());
```

This StorePath would also automatically implement `IntoStoreId` making it painless to use, but still gives enough flexibility for the next point.

The store, in `get_item` would take out the `module` part (the first argument to the macro) and search for all folders in the root folder using a regex akin to `{modulename}-[^-]*"`. It then filters out all *incompatible* files and matches those against the store path itself.

For `get_all_for` it would simply merge the folders together and return the array like that, the incompatible ones are marked as "NOT COMPTIBLE", using an enum would make sense.

One might think that duplicate entries are possible this way, however I believe that they can be future proofed like this:

Scenario 1:

1. LibX links to `bm` version 2.2
2. LibX creates a bookmark called `zwitschern`
3. The store creates a file in `$IMAGE_ROOT/bm-0.2/zwitschern`

Now, if a crate using version 1.5 will try and look for `zwitschern` it will simply get back an empty enum of the variant `Incompatible`.
However, if a crate using version 2.9 will try to look at the file, it should return the correct entry.

Scenario 2:

1. LibY links to `bm` version 1.3, creates file with `bm` called `foo`
2. LibX links to `bm` version 2.5, tries to load file from `bm` called `foo`

In this case it should get a variant of the type `Possibly Deprecated`. Thus the new library has the choice of either `importing` said file by reading it, transforming possibly and writing it back under it's new version. The choice lies in the library, and should possibly only be done when the user agrees to it. 

Or the Library chooses to not `import` it and writes it back to it's original position. An example:

```rust
fn get_friends_by_name(&self, name: String) -> Vec<FriendEntry> { # Implents RustcEncodable
    let friends = Vec::new();
    for entry in self.store.get_all(contacts::ModulePath::root()) {
        match entry {
            Entry::Normal(e) => {
                let friend = FriendEntry::from_entry(e).unwrap();
                if friend.name == name { 
                    friends.append(friend) 
                }
            },
            Entry::PossiblyDeprecated(e) => {
                let friend = FriendEntry::from_entry(e);
                if friend.is_some() {
                    let friend = friend.unwrap();
                    if friend.name == name { 
                        friends.append(friend) 
                    }
                }
            },
            _ => {} # Do nothing otherwise
        }
    }
}
```

What do you think?

**Comment by matthiasbeyer** [comment]
I consider your thoughts useful, yes. But let me note some things:

---

First, the positivie: It is a really good idea to encode the module in the filename. This way one doesn't have to load all files when (for example) listing all bookmarks. It decreases flexibility for the user a bit, though, as the filename has a part he must not alter.

---

I really like the approach with the `ModulePath`, but: A module-path should put the _module name_ in the _file name_. This way, the user is free in where to place the file and his folder-structures are completely flexible.

Paths would look like (`/` beeing the store directory):

* `/some-folder/cats/bm-funnycats.ext`
* `/something-else/not_cats/bm-dogs.ext`

-> (For example) Bookmarks can be placed everywhere in the file-tree, not just in `/bm/*`. You know what I mean?

---

I'd also use another name, something like `StorePath` or such... we are not having a path to a module, but a path to a module entry. So maybe even `ModuleEntryPath` would be sufficient.

---

I'm not sure whether we want to encode the version in the path, though. I consider the header of the file the right place for this, actually. And that's what `libimagmodule` can implement for all modules! :smile:

**Comment by TheNeikos** [comment]
> I'm not sure whether we want to encode the version in the path, though. I consider the header of the file the right place for this, actually. And that's what libimagmodule can implement for all modules! :smile:

Sure, advantage is that you don't have to load the file to know whether it will parse correctly or not.

> I'd also use another name, something like StorePath or such... we are not having a path to a module, but a path to a module entry. So maybe even ModuleEntryPath would be sufficient.

That's just bikeshedding :)

> I really like the approach with the ModulePath, but: A module-path should put the module name in the file name. This way, the user is free in where to place the file and his folder-structures are completely flexible.

I would agree in theory that freedom is nice, but it comes at a cost. And I see no reason for this cost here. Why would you need to glob the *whole* store to find things belonging to bm?

I am open for counter examples though. (Real use cases)

> First, the positivie: It is a really good idea to encode the module in the filename. This way one doesn't have to load all files when (for example) listing all bookmarks. It decreases flexibility for the user a bit, though, as the filename has a part he must not alter.

No it doesn't. The store is basically "**Here be dragons**" just like the `.git` folder. Sure you can go in and look at stuff, but unless you know what you are doing you might just break it. So I see no problem with assuming a few invariants when dealing with the files. 

*This is the same as my previous point*

**Comment by matthiasbeyer** [comment]
I guess you're right.

I'd then propose the following path, starting from the store-root:

```
/<module>/<version>/<filename>.<ext>
```

---

Anyways, if you say that "Here be dragons" in the store, it doesn't make that much sense anymore to let the user define the filename(, except for linkability, which is a *huge* point, actually). I'd like to hear your opinions on how to define (from a users perspective) the filename of a new entry (let it be a `bm` or whatever, doesn't matter).

**Comment by TheNeikos** [comment]
> Anyways, if you say that "Here be dragons" in the store, it doesn't make that much sense anymore to let the user define the filename(, except for linkability, which is a huge point, actually).

I agree here, however it does not change my original point! If the user puts in a path or the library generates a bad path then it is their own fault and they will get an error thrown to the face.

However that is the risk already today with a variety of tools. Try out `echo > -l; ls *` and you will see that not being careful is already a problem today and it is accepted as it allows generally better flexibility.

---

Having the version in the path works just as well, might be even less buggy than my proposal.

**Comment by matthiasbeyer** [comment]
I did not mean that the user does something like `cat <<EOS >> ~/.imag/store/bm/0.1/foo`, but that the user uses the normal commandline tools to generate a new entry in the store. How is the filename generated? I mean, normally, filenames have some meaning to the user. If the store is (as you proposed and as I see makes sense) hidden from the user, it doesn't make sense anymore for the user to define the filename. So it has to be generated _somehow_.

Which brings me to the next point: If a user wants to link two bookmarks, he has to identify either of them. How is that done? The initial thought was to do it with the path of one of the entries. If you generate them, this gets more complicated for the user. If you do not, you have to ask the user for the filename when generating the file.

Either way: Is the _whole_ path included in the link? I mean, does the user link by specifying `bm/0.1/foo` or does the user link with `foo` (which means the name must be unique over versions)?

**Comment by TheNeikos** [comment]
> How is the filename generated?

That is a library question, so you are literally free to do what you want?

> How is that done?

See above

> I mean, does the user link by specifying bm/0.1/foo or does the user link with foo (which means the name must be unique over versions)

The latter, one would just put in `foo` to link to that entry. The store then serves an entry based on the version of the requesting library, allowing the library to handle the case of the file being not meant for them.

**Comment by matthiasbeyer** [comment]
> > I mean, does the user link by specifying bm/0.1/foo or does the user link with foo (which means the name must be unique over versions)
> The latter, one would just put in foo to link to that entry. The store then serves an entry based on the version of the requesting library, allowing the library to handle the case of the file being not meant for them.

And what if you have an entry `/bm/0.a/foo` and `/music/0.b/foo`? How'd you know which one is the right one if you just link to `foo`?

**Comment by TheNeikos** [comment]
That would not be possible, and should be disallowed by the store. Which is part of why I wanted to put the version in the filename. Should a user feel the *urge* to create files manually for some reason they would at least find it easy to see for duplicate names.

Although I envisioned it more like this: `cat my_file | imag store --module bm 'foo'` and would be a lot safe for the user :) No need to poke around manually, which again leaves us pretty gimped.

**Comment by matthiasbeyer** [comment]
The version wouldn't be enough. The module would be needed as well, and this leads us back to file names like

```
<module>-<version>-<custom>.<ext>
```

Which would then also be required for linking (except the `ext` part, of course). And this would still get a bit funky if we update file versions. Consider an URL stored in the `bm` module with path `bm-0.1-kittens.ext`. Now update the `bm` version to `0.2`, including automatically store-entry updating. All links to `bm-0.1-kittens` would need an update now.

---

Maybe we have to argue this in person to work out a flexible yet powerful scheme.

---

Just besides: `cat my_file | imag store --module bm --version "1.2" --raw 'foo'` would not work that nicely, as the header wouldn't be written. You would need something like

```
imag store --module bm \
  --version 1.2 \
  --raw 'foo' \
  --header imag.content.uri="http://andso.on" \
  --header bm.tags="kittens,cats,cute"
```
_line breaks for readability_

(no `cat...|` as the `bm` module would not contain a `content` section, so there is no point in `cat`ing content into the store entry. But yes, I know what you mean)

**Comment by TheNeikos** [comment]
The raw switch would replace the whole file, putting the danger in the user's hands. Which in this case is *everything* header and content. But sure I don't mind discussing this in person.

**Comment by neithernut** [comment]
Another thing which should be taken into account: lifting items to another version (so you don't end up with a bunch of legacy-stuff).

----

I'd like to join such a discussion, so let me know when you're having it. Maybe I can join.

**Comment by matthiasbeyer** [comment]
We're having it _now_.
