### ISSUE TITLE
Redefine the Store interface

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#76]
- [ ] Create
- [ ] Read
- [ ] Update
- [ ] Delete
- [ ] exported types

Each of these will be tracked in own issues:

#77 , #78 , #79 , #80 and #81

**Comment by matthiasbeyer** [comment]
@neithernut Feel free to submit PRs or comments on this and the related issues for defining the store {file format, interface} with me.

PRs to the document are welcome as well.

**Comment by matthiasbeyer** [comment]
When we implement the store interface, we should take multithreading into account and export the types appropriately.

Changes to the store should be done as transactions and the store should have an internal cache, writing to FS at the latest possible time.

**Comment by TheNeikos** [comment]
If you put the issue number into the checklist to their corresponding number it should get checked once that issue is closed!

**Comment by neithernut** [comment]
Currently thinking about this, but I currently lack time. You can assign this to me, if you want (and blame me if I didn't come up with anything yet on Thursday).

**Comment by matthiasbeyer** [comment]
@neithernut I cannot assign you, as github does not offer this as an option for non-organization repositories, at least not as long as I don't give you push access. And of course I won't give you push access.

**Comment by neithernut** [comment]
Yep, I forgot...
Well, I'll try to take some time to work on this issue.

**Comment by neithernut** [comment]
So after thinking about this, I hit some things which definitely should be considered when defining an interface:

### File-system synchronization

We don't want to allow messing things up when running multiple `imag` commands in parallel. Hence, we definitely want to `flock()` the file when altering it, ensuring that the file experiences only one edit at a time. Locking it when doing a read is also generally a good idea. Alternatively, one can use a "shared lock" when retrieving an item, knowing it will only be read.
Now for read-only access of items, it would be nice if we could, at some point, release the file, leaving us with a read-only version of the item. Use-cases include, of course, commands which will retrieve some information without altering the item itself (most commands, I guess), without the chance of reading the file while someone else is writing to it.
This could be done by defining two traits: one trait describing read-only items and one trait, which extends (not quite sure about the rust semantics) the first one by read-write-access and a function which will create a read-only item, destroy the read-write item and release the file, preferably in that order.

### In-process locking

Transaction based access would be nice for a lot of stuff, but it would be very impractical to implement and yield very little benefits. Instead, I'd like to apply similar restrictions as is imposed on the file-system-level: allow only one mutable representation of an item at a time, but as many read-only versions as the user may like to have around. Doing this is trivial given the traits laid out above: one only has to ensure that the user can only retrieve items via a few interfaces, all of which use a sort of reservation-mechanism during item creation. One may even rely on the flock mechanism inside the process (e.g. subsequent `flock()` calls on fds of the same file will block each other). But we should investigate whether we can trust this behaviour `flock()` (this also a question of portability).

### Concrete impacts on the interface

 * The two traits I proposed should at least be defined in an abstract ways
 * The create call returns a mutable item. Albeit, one has to take error and race conditions into account. Hence, the return-value should be an optional.
 * There should be two read- or load-calls: one will yield a mutable item, one will yield an immutable.
 * The update-call should only be defined for mutable items.
 * So does the delete-call, I guess. Not sure about this one

### Implementation details

This is not exactly relevant for the interface, but I'd like to dump this thought as an additional information.
Internally, we should have a struct which performs the `flock()` call, releasing the file when the struct/object dies. This struct may then be referenced by all item structs reflecting the file's contents read only. It may also be _included_ in structs representing modifiable items. This way we can pull items from the store for editing and be sure that they will not be modified behind our backs', at least not by complying software.
Also note that file locks can be used in shell-scripts.

----

I'm sorry to always blurt out stuff this late, but some things came up this weekend, so I don't have as much time as I hoped.

**Comment by neithernut** [comment]
A note about why you should hold a lock on immutable items: this actually only makes sense if you don't read the entire file in one go. This might, for example, be the case if you access the contents of the item.

**Comment by neithernut** [comment]
In this context, I mean "holding a lock throughout the in-memory-object's lifetime". You definitely want to hold a lock during (initial) reads.

**Comment by TheNeikos** [comment]
That is an interesting thought, going with existing implementations of locking mechanisms one could make a struct called `LockedFile`, which just holds a path at first, and one can then call `.lock()` or `lock_mut()`, and obviously their `try_lock{,_mut}` counterpart. This would also play nicely with Rust's type system, giving you either a read only file, or a read/write file handle.

**Comment by matthiasbeyer** [comment]
As far as I can see, both of you talk about the _implementation_ of the store. I am talking about the _interface the store library exports_, which is, IMHO, another problem.

Can we please talk about the interface, which is more important? Locking and stuff is not exported by the store library at all and is therefor an implementation detail!

**Comment by neithernut** [comment]
I _was_ talking about the interface, see section "Concrete impacts on the interface". Also, I pretty much consider the behaviour of the items with regard to threading as an important point of the interface, which should be documented.

**Comment by matthiasbeyer** [comment]
@neithernut okay...

> The two traits I proposed should at least be defined in an abstract way

We don't need two traits, as explained in the following.

> The create call returns a mutable item. Albeit, one has to take error and race conditions into account. Hence, the return-value should be an optional.

Of course.

> There should be two read- or load-calls: one will yield a mutable item, one will yield an immutable.

If we take multithreading into account, this can easily be done with the same interface: If an Entry is returned encapsulated into `Arc<RWLock<Entry>>` everything you propose is already available.

> The update-call should only be defined for mutable items.

This point can be omitted after the latter.

> So does the delete-call, I guess. Not sure about this one

I don't think so, as deleting a file has nothing to do with its content. So removing a file from the store should be done via path.

The implementation of `delete()` should do one crucial thing, though: Mark an Path as removed and keep this mark internally. As other threads may hold a reference to the file and alter it (in-memory), the filesystem-level delete should be cached until the store gets deinitialized. This way we are rather secure when it comes to race conditions.

**Comment by matthiasbeyer** [comment]
What I'd do, what @neithernut proposed: Define the store as trait. This way, we won't have any hassle when we want to switch the store implementation at some point (thinking about one-shot vs. long-running processes here, which we might have later).

**Comment by matthiasbeyer** [comment]
Another point which pops up in my head right now: We could also define the `Entry` (and `EntryHeader`, `EntryContent`) types as traits and simply serve default implementations for `std::fs::File` - This way we have flexibility there as well if we want to change things later on.

@TheNeikos does this complicate the interface? I mean if we return `Arc<RWLock<Trait>>` instead of `Arc<RWLock<Struct>>`? I don't think so, right?

**Comment by neithernut** [comment]
I agree on the point that we can omit one trait if we limit the `update()` call as suggested by @matthiasbeyer.
Is `RWLock<>` a trait? If it is linked to a concrete implementation, it is not sufficient as we cannot perform proper file-system-locking. At this point, we should probably move the discussion to you pull-request, which I see already saw some refining.

**Comment by matthiasbeyer** [comment]
No! Lets keep the discussion here, so we have only _one_ thread where the discussion is located at.

---

The file-system locking could be done by another trait. There's a [crate](https://crates.io/crates/fs2/) available which does file-system `flock`ing. So we would export:

```rs
Arc<RWLock<FileExt<Entry>>>
```

whereas Entry is our trait, if we realize it as a trait. The order of the above might be relevant... I'm not sure here, maybe @TheNeikos knows?

**Comment by neithernut** [comment]
Ok, then we'll keep the discussion here.

----

My point is: we (only?) need fs-locking. If we do in-process-locking, it should perfectly mirror the behaviour of the "external" file-lock.
Also, the lock has so live until the item is destroyed or made immutable (in this context, immutability may be expressed apart from the rust semantics. By your semantics, for example, an `Entry` would be immutable when the possibility to feed it to `update()` is obstructed through the type system). Hence, at least the possibility of carrying a lock on a file  _must_ be provided by the wrapper or the type of the entry. We can implement the `FileExt` trait, but we should consider possible abuse. A user should, for example, never be able to lock an `Entry` in any way after it is initially constructed.

**Comment by matthiasbeyer** [comment]
> we (only?) need fs-locking.

No, we need both. `flock`ing is only process-bound, not thread-bound. What you mean is that one process loads the file twice, but the store shouldn't do that! The store should know whether a path is already loaded and shouldn't do any FS action if the file is already in memory.

> the lock has so live until the item is destroyed

This is what Rust does for us

> or made immutable (in this context, immutability may be expressed apart from the rust semantics

No. Why? I mean, the Rust semantics are there to use them. No need to do it in another way.

> By your semantics, for example, an Entry would be immutable when the possibility to feed it to update() is obstructed through the type system).

I do not understand this one. The `Entry` inside the `Arc<...>` is not mutable and can be fetched from the `RWLock` wrapper in a mutable way... everything is fine! Or do I overlook something?

> We can implement the FileExt trait, 

`FileExt` is already implemented for `fs::File` by the library I named. 

> but we should consider possible abuse. A user should, for example, never be able to lock an Entry in any way after it is initially constructed.

I agree with you that the user of `libimagstore` should not be able to interact with the `FileExt` implementation and we should hide that, so the user is not able to `unlock()` the file, for example.

Here comes into play what I've suggested: The `Entry` Type does not hold the `fs::File` it is ready from. It just holds the `PathBuf` to the actual file. The Store should internally cache the `File` object, but the `libimagstore` does not export filesystem-files (This can btw later be used to implement an in-memory store for testing). This way, the store would lock the filesystem-file, but the user of the lib would only see content.

**Comment by neithernut** [comment]
I have to revise the point I made that a file-lock has to live until the item itself dies. As I already wrote before that statement, it is sufficient it if lives until the file is read, for the read-only-case. I'm sorry about this mistake I made, because it may have lend to some misunderstandings.

----

> No, we need both. flocking is only process-bound, not thread-bound. What you mean is that one process loads the file twice, but the store shouldn't do that! The store should know whether a path is already loaded and shouldn't do any FS action if the file is already in memory.

You are not completely right. From the (linux) man-page:

> If a process uses open(2) (or similar) to obtain more than one descriptor for the same file, these descriptors are treated independently by flock(). An attempt to lock the file using one of these file descriptors may be denied by a lock that the calling process has already placed via another descriptor.

As you can see, at least on linux a lock held by a process via one fd may also affects other other fds on the same file. You _can_, principally, use `flock()` for in-process synchronization. Question is what the "may" in the last sentence I quoted means for programmers in practice. You _may_ be right in saying that `flock()` is insufficient for multi-threading applications, but you can't generally deny it either without looking at what linux and BSDs are actually doing. Since it seems only sensible to impose this restriction when implementing `flock()`, my _guess_ is that it's sufficient.


> > the lock has so live until the item is destroyed
> This is what Rust does for us

No, not if the lock is implemented as a wrapper around a datatype. It is trivial to unwrap the inner item. In this instance, the lock may be released. If the user wraps the lock _again_, you have a loophole by which the user may end up with interleaved reads and writes by separate processes.
You are essentially fooling yourself by trusting in the language alone without considering the _exact_ semantics and consequences.


> > or made immutable (in this context, immutability may be expressed apart from the rust semantics
> No. Why? I mean, the Rust semantics are there to use them. No need to do it in another way.

Because we are talking about inherently different things here. The rust-semantics of mutability do (to my knowledge) not deal with possible actions and restrictions linked to changes of mutability on this plane. In our example, we do want to unlock a file when an item gets immutable. How do you enforce this when using rusts mutability semantics alone? How do you model that an immutable item must _never ever_ become mutable again?


> > By your semantics, for example, an Entry would be immutable when the possibility to feed it to update() is obstructed through the type system).
> I do not understand this one. The Entry inside the Arc<...> is not mutable and can be fetched from the RWLock wrapper in a mutable way... everything is fine! Or do I overlook something?

I tried as hard as I could to make this clear: I'm not talking language-level. I'm talking about the behaviour of the system itself. An item is immutable if it can't be changed anymore, e.g. "not written to disk". Maybe I should have used other terms, like "read-only" and "read-write". If you finally understood this one, the other points should be clear to you as well.


> Here comes into play what I've suggested: The Entry Type does not hold the fs::File it is ready from. It just holds the PathBuf to the actual file. The Store should internally cache the File object, but the libimagstore does not export filesystem-files (This can btw later be used to implement an in-memory store for testing). This way, the store would lock the filesystem-file, but the user of the lib would only see content.

You didn't talk about centralized _storage_ of the actual data before. In this light, it makes sense to have the data and the lock handling data in one place. But you now have to communicate changes in mutability (again, _not_ talking about rust's mutability concept) to the store in some way. This makes sense, but also increases the system's complexity because you now have to communicate and react on changes of the item's state (including it's mutability). In this scenario using a mere `RWLock` is just not sufficient. A number of scenarios where things can go horribly wrong pop into my mind instantly.
The only option to avoid the emerging issues would be to hold an exclusive file-lock over the entire life-time of the central storage of an item and this would be just stupid. Again, as I write, I instantly get ideas of use-cases which would be obstructed by such a design decision. For example: consider a "viewer" blocking a storage-wide search because they both want to read(!) the item.

**Comment by matthiasbeyer** [comment]
After re-reading your post two times... I guess yes, I can now understand what you mean, and I see what you mean now.

But now: What do you propose in manner of interface code? To my knowledge, we're argueing over the read/update calls only, the others are not critical. As far as I understand you, you want to export

* read() in two variants:
  * One time returning an Entry not mutable, R-`flock`ed File on the FS
  * One time returning an Entry mutable and RW-`flock`ed on the FS

both of these instances shall `unlock()` on `Drop` and both of them should be capable of Multithreading within the application.

* The `update()` action works only with the mutable variant, of course.

"mutable" and "unmutable" are "on filesystem level" _as well as_ on type-system level in this case (why would one change an entry in-memory if you cannot change it on disk...).

Do I summarize this correctly? If yes, feel free to propose code!

**Comment by neithernut** [comment]
Yes, you got it mostly. I just want to clarify a few last things:
 * The version of `read()` returning an immutable entry does only need to lock the file during read, _if_ the file is read into memory in one go. This is only relevant when defining the semantics of the calls: we can allow `read()` to return unlocked, immutable entries and require the dropping mechanism to deal with these cases correctly.
 * It is imperative that the user can not unlock the file without dropping/destructing the entry.
 * One possible use-case of having both read-only and "write-back-enabled" instances would be a program keeping around a bunch of items for queries on one hand while, on another hand, allowing editing items. If the item to be edited happen to be in the cache already, one may want to pull a "write-back-enabled" version from the store for editing, compare it with the version kept around and update that version, maybe with the user's consent or informing her in the process. This would require either the programmer to use a datastructure where you can replace items or entries read pulled the store to be swappable or writeable even if they never can be written back.

----

Yes, I discussed problems emerging when we have concurrent access of the store from possibly multiple processes. And I oppose ignoring them, because having to redesign an existing core interface afterwards is a pain in the ass.

So, do you accept my proposal, at least on an abstract level?

**Comment by matthiasbeyer** [comment]
> So, do you accept my proposal, at least on an abstract level?

Yes. Please:

* send a PR to the document
* send a PR which contains the interface-code (to #95 if you want to)

**Comment by neithernut** [comment]
Ok, I'll try to do this as soon as I can spare some time. You might have to wait until tomorrow.

**Comment by matthiasbeyer** [comment]
@neithernut Have a look at https://github.com/matthiasbeyer/playground.rs/blob/flocking/src/flocking.rs - Is this what we want? If yes, I'll import this work into the codebase of `imag`!

**Comment by neithernut** [comment]
I had less time than expected today, so I'm not gonna push anything today :(
I'll look at the link you provided and then, finally, push something.

**Comment by matthiasbeyer** [comment]
For readers:

The discussion on this whole topic happened in #98 mainly, but also #95 and in #99 where we came to a solution (it seems so at the time of writing this, at least).

The whole issue plus its sub-issues will be closed if #99 gets merged.

**Comment by matthiasbeyer** [comment]
Done with #99.
